<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251010155237 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE BAPIKEYS (BID BIGINT AUTO_INCREMENT NOT NULL, BOWNERID BIGINT NOT NULL, BKEY VARCHAR(64) NOT NULL, BSTATUS VARCHAR(16) NOT NULL, BLASTUSED BIGINT DEFAULT 0 NOT NULL, BSCOPES JSON NOT NULL, BCREATED BIGINT NOT NULL, BNAME VARCHAR(128) DEFAULT \'\' NOT NULL, UNIQUE INDEX UNIQ_16D420BFF32F7F9B (BKEY), INDEX idx_apikey_key (BKEY), INDEX idx_apikey_owner (BOWNERID), INDEX idx_apikey_status (BSTATUS), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BCONFIG (BID BIGINT AUTO_INCREMENT NOT NULL, BOWNERID BIGINT NOT NULL, BGROUP VARCHAR(64) NOT NULL, BSETTING VARCHAR(96) NOT NULL, BVALUE VARCHAR(250) NOT NULL, INDEX idx_config_lookup (BOWNERID, BGROUP, BSETTING), INDEX idx_group (BGROUP), INDEX idx_setting (BSETTING), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BMESSAGEMETA (BID BIGINT AUTO_INCREMENT NOT NULL, BMESSAGEID BIGINT NOT NULL, BMETAKEY VARCHAR(64) NOT NULL, BMETAVALUE LONGTEXT NOT NULL, BCREATED BIGINT NOT NULL, INDEX idx_messagemeta_message (BMESSAGEID), INDEX idx_messagemeta_key (BMETAKEY), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BMESSAGES (BID BIGINT AUTO_INCREMENT NOT NULL, BUSERID BIGINT NOT NULL, BTRACKID BIGINT NOT NULL, BPROVIDX VARCHAR(96) NOT NULL, BUNIXTIMES BIGINT NOT NULL, BDATETIME VARCHAR(20) NOT NULL, BMESSTYPE VARCHAR(4) DEFAULT \'WA\' NOT NULL, BFILE SMALLINT NOT NULL, BFILEPATH VARCHAR(255) NOT NULL, BFILETYPE VARCHAR(8) NOT NULL, BTOPIC VARCHAR(16) DEFAULT \'UNKNOWN\' NOT NULL, BLANG VARCHAR(2) DEFAULT \'NN\' NOT NULL, BTEXT LONGTEXT NOT NULL, BDIRECT VARCHAR(3) DEFAULT \'OUT\' NOT NULL, BSTATUS VARCHAR(24) NOT NULL, BFILETEXT LONGTEXT NOT NULL, INDEX BUSERID (BUSERID), INDEX BTRACKID (BTRACKID), INDEX BMESSTYPE (BMESSTYPE), INDEX BFILE (BFILE), INDEX BDIRECT (BDIRECT), INDEX BLANG (BLANG), INDEX BTOPIC (BTOPIC), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BMODELS (BID BIGINT AUTO_INCREMENT NOT NULL, BSERVICE VARCHAR(32) NOT NULL, BNAME VARCHAR(48) NOT NULL, BTAG VARCHAR(24) NOT NULL, BSELECTABLE INT NOT NULL, BPROVID VARCHAR(96) NOT NULL, BPRICEIN DOUBLE PRECISION NOT NULL, BINUNIT VARCHAR(24) NOT NULL, BPRICEOUT DOUBLE PRECISION NOT NULL, BOUTUNIT VARCHAR(24) NOT NULL, BQUALITY DOUBLE PRECISION NOT NULL, BRATING DOUBLE PRECISION NOT NULL, BISDEFAULT INT DEFAULT 0 NOT NULL, BJSON JSON NOT NULL, INDEX idx_tag (BTAG), INDEX idx_service (BSERVICE), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BPROMPTMETA (BID BIGINT AUTO_INCREMENT NOT NULL, BPROMPTID BIGINT NOT NULL, BMETAKEY VARCHAR(64) NOT NULL, BMETAVALUE LONGTEXT NOT NULL, BCREATED BIGINT NOT NULL, INDEX idx_promptmeta_prompt (BPROMPTID), INDEX idx_promptmeta_key (BMETAKEY), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BPROMPTS (BID BIGINT AUTO_INCREMENT NOT NULL, BOWNERID BIGINT NOT NULL, BLANG VARCHAR(2) DEFAULT \'en\' NOT NULL, BTOPIC VARCHAR(64) NOT NULL, BSHORTDESC LONGTEXT NOT NULL, BPROMPT LONGTEXT NOT NULL, INDEX BTOPIC (BTOPIC), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BRAG (BID BIGINT AUTO_INCREMENT NOT NULL, BUID BIGINT NOT NULL, BMID BIGINT NOT NULL, BGROUPKEY VARCHAR(64) NOT NULL, BTYPE INT NOT NULL, BSTART INT NOT NULL, BEND INT NOT NULL, BTEXT LONGTEXT NOT NULL, BEMBED VECTOR(1024) NOT NULL COMMENT \'(DC2Type:vector)\', BCREATED BIGINT NOT NULL, INDEX idx_rag_user (BUID), INDEX idx_rag_message (BMID), INDEX idx_rag_group (BGROUPKEY), INDEX idx_rag_type (BTYPE), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BRATELIMITS_CONFIG (BID BIGINT AUTO_INCREMENT NOT NULL, BSCOPE VARCHAR(64) NOT NULL, BPLAN VARCHAR(32) NOT NULL, BLIMIT INT NOT NULL, BWINDOW INT NOT NULL, BDESCRIPTION LONGTEXT NOT NULL, BCREATED BIGINT NOT NULL, BUPDATED BIGINT NOT NULL, INDEX idx_ratelimit_scope (BSCOPE), INDEX idx_ratelimit_plan (BPLAN), UNIQUE INDEX unique_scope_plan (BSCOPE, BPLAN), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BSESSIONS (BID VARCHAR(128) NOT NULL, BUSERID BIGINT DEFAULT NULL, BTOKEN VARCHAR(128) NOT NULL, BDATA LONGTEXT NOT NULL, BCREATED BIGINT NOT NULL, BLASTACTIVITY BIGINT NOT NULL, BEXPIRES BIGINT NOT NULL, BIPADDRESS VARCHAR(45) DEFAULT \'\' NOT NULL, BUSERAGENT VARCHAR(255) DEFAULT \'\' NOT NULL, UNIQUE INDEX UNIQ_2F1CE1199D139E52 (BTOKEN), INDEX idx_session_user (BUSERID), INDEX idx_session_token (BTOKEN), INDEX idx_session_expires (BEXPIRES), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BTOKENS (BID BIGINT AUTO_INCREMENT NOT NULL, BUSERID BIGINT NOT NULL, BTOKEN VARCHAR(255) NOT NULL, BTYPE VARCHAR(32) NOT NULL, BCREATED BIGINT NOT NULL, BEXPIRES BIGINT NOT NULL, BUSED TINYINT(1) DEFAULT 0 NOT NULL, BUSEDDATE BIGINT DEFAULT NULL, BIPADDRESS VARCHAR(45) DEFAULT \'\' NOT NULL, UNIQUE INDEX UNIQ_A598CC859D139E52 (BTOKEN), INDEX idx_token_user (BUSERID), INDEX idx_token_token (BTOKEN), INDEX idx_token_type (BTYPE), INDEX idx_token_expires (BEXPIRES), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BUSELOG (BID BIGINT AUTO_INCREMENT NOT NULL, BUSERID BIGINT NOT NULL, BUNIXTIMES BIGINT NOT NULL, BACTION VARCHAR(64) NOT NULL, BPROVIDER VARCHAR(32) DEFAULT \'\' NOT NULL, BMODEL VARCHAR(128) DEFAULT \'\' NOT NULL, BTOKENS INT DEFAULT 0 NOT NULL, BCOST NUMERIC(10, 6) DEFAULT \'0\' NOT NULL, BLATENCY INT DEFAULT 0 NOT NULL, BSTATUS VARCHAR(16) DEFAULT \'success\' NOT NULL, BERROR LONGTEXT NOT NULL, BMETADATA JSON NOT NULL, INDEX idx_uselog_user (BUSERID), INDEX idx_uselog_time (BUNIXTIMES), INDEX idx_uselog_action (BACTION), INDEX idx_uselog_provider (BPROVIDER), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BUSER (BID BIGINT AUTO_INCREMENT NOT NULL, BCREATED VARCHAR(20) NOT NULL, BINTYPE VARCHAR(4) DEFAULT \'WEB\' NOT NULL, BMAIL VARCHAR(128) NOT NULL, BPW VARCHAR(64) NOT NULL, BPROVIDERID VARCHAR(32) NOT NULL, BUSERLEVEL VARCHAR(32) DEFAULT \'NEW\' NOT NULL, BEMAILVERIFIED TINYINT(1) DEFAULT 0 NOT NULL, BUSERDETAILS JSON NOT NULL, BPAYMENTDETAILS JSON NOT NULL, INDEX BMAIL (BMAIL), INDEX BINTYPE (BINTYPE), INDEX BPROVIDERID (BPROVIDERID), INDEX BUSERLEVEL (BUSERLEVEL), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BVERIFICATION_TOKENS (BID BIGINT AUTO_INCREMENT NOT NULL, BUID BIGINT NOT NULL, BTOKEN VARCHAR(64) NOT NULL, BTYPE VARCHAR(32) NOT NULL, BCREATED BIGINT NOT NULL, BEXPIRES BIGINT NOT NULL, BUSED TINYINT(1) DEFAULT 0 NOT NULL, UNIQUE INDEX UNIQ_54AC53F9D139E52 (BTOKEN), INDEX IDX_54AC53F2A24D234 (BUID), INDEX idx_token (BTOKEN), INDEX idx_expires (BEXPIRES), PRIMARY KEY(BID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE BAPIKEYS ADD CONSTRAINT FK_16D420BFD969E21A FOREIGN KEY (BOWNERID) REFERENCES BUSER (BID)');
        $this->addSql('ALTER TABLE BMESSAGEMETA ADD CONSTRAINT FK_F2A54B27EA4931D2 FOREIGN KEY (BMESSAGEID) REFERENCES BMESSAGES (BID)');
        $this->addSql('ALTER TABLE BPROMPTMETA ADD CONSTRAINT FK_D44C7DE359DEE83D FOREIGN KEY (BPROMPTID) REFERENCES BPROMPTS (BID)');
        $this->addSql('ALTER TABLE BRAG ADD CONSTRAINT FK_7EBB1F032A24D234 FOREIGN KEY (BUID) REFERENCES BUSER (BID)');
        $this->addSql('ALTER TABLE BRAG ADD CONSTRAINT FK_7EBB1F03381120FC FOREIGN KEY (BMID) REFERENCES BMESSAGES (BID)');
        $this->addSql('ALTER TABLE BSESSIONS ADD CONSTRAINT FK_2F1CE119FEF0B465 FOREIGN KEY (BUSERID) REFERENCES BUSER (BID)');
        $this->addSql('ALTER TABLE BTOKENS ADD CONSTRAINT FK_A598CC85FEF0B465 FOREIGN KEY (BUSERID) REFERENCES BUSER (BID)');
        $this->addSql('ALTER TABLE BUSELOG ADD CONSTRAINT FK_271BCC23FEF0B465 FOREIGN KEY (BUSERID) REFERENCES BUSER (BID)');
        $this->addSql('ALTER TABLE BVERIFICATION_TOKENS ADD CONSTRAINT FK_54AC53F2A24D234 FOREIGN KEY (BUID) REFERENCES BUSER (BID)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE BAPIKEYS DROP FOREIGN KEY FK_16D420BFD969E21A');
        $this->addSql('ALTER TABLE BMESSAGEMETA DROP FOREIGN KEY FK_F2A54B27EA4931D2');
        $this->addSql('ALTER TABLE BPROMPTMETA DROP FOREIGN KEY FK_D44C7DE359DEE83D');
        $this->addSql('ALTER TABLE BRAG DROP FOREIGN KEY FK_7EBB1F032A24D234');
        $this->addSql('ALTER TABLE BRAG DROP FOREIGN KEY FK_7EBB1F03381120FC');
        $this->addSql('ALTER TABLE BSESSIONS DROP FOREIGN KEY FK_2F1CE119FEF0B465');
        $this->addSql('ALTER TABLE BTOKENS DROP FOREIGN KEY FK_A598CC85FEF0B465');
        $this->addSql('ALTER TABLE BUSELOG DROP FOREIGN KEY FK_271BCC23FEF0B465');
        $this->addSql('ALTER TABLE BVERIFICATION_TOKENS DROP FOREIGN KEY FK_54AC53F2A24D234');
        $this->addSql('DROP TABLE BAPIKEYS');
        $this->addSql('DROP TABLE BCONFIG');
        $this->addSql('DROP TABLE BMESSAGEMETA');
        $this->addSql('DROP TABLE BMESSAGES');
        $this->addSql('DROP TABLE BMODELS');
        $this->addSql('DROP TABLE BPROMPTMETA');
        $this->addSql('DROP TABLE BPROMPTS');
        $this->addSql('DROP TABLE BRAG');
        $this->addSql('DROP TABLE BRATELIMITS_CONFIG');
        $this->addSql('DROP TABLE BSESSIONS');
        $this->addSql('DROP TABLE BTOKENS');
        $this->addSql('DROP TABLE BUSELOG');
        $this->addSql('DROP TABLE BUSER');
        $this->addSql('DROP TABLE BVERIFICATION_TOKENS');
    }
}
