<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Rate Limiting Configuration Data Migration
 * 
 * Populates BCONFIG table with rate limit configurations for all user levels:
 * - ANONYMOUS: Not phone verified, very restricted
 * - NEW: Phone verified, lifetime limits
 * - PRO/TEAM/BUSINESS: Paid plans with hourly/monthly limits
 */
final class Version20251017100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Populate rate limiting configuration data in BCONFIG table';
    }

    public function up(Schema $schema): void
    {
        // Clean existing rate limit configs
        $this->addSql("DELETE FROM BCONFIG WHERE BGROUP LIKE 'RATELIMITS_%' AND BOWNERID = 0");
        $this->addSql("DELETE FROM BCONFIG WHERE BGROUP = 'SYSTEM_FLAGS' AND BOWNERID = 0");

        // System Flags
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'SYSTEM_FLAGS', 'SMART_RATE_LIMITING_ENABLED', '1')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'SYSTEM_FLAGS', 'RATE_LIMITING_DEBUG_MODE', '0')");

        // ANONYMOUS User Limits (NOT PHONE VERIFIED - VERY RESTRICTED)
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_ANONYMOUS', 'MESSAGES_TOTAL', '10')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_ANONYMOUS', 'IMAGES_TOTAL', '2')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_ANONYMOUS', 'VIDEOS_TOTAL', '0')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_ANONYMOUS', 'AUDIOS_TOTAL', '0')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_ANONYMOUS', 'FILE_ANALYSIS_TOTAL', '3')");

        // NEW User Limits (PHONE VERIFIED - LIFETIME TOTALS - NEVER RESET)
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_NEW', 'MESSAGES_TOTAL', '50')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_NEW', 'IMAGES_TOTAL', '5')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_NEW', 'VIDEOS_TOTAL', '2')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_NEW', 'AUDIOS_TOTAL', '3')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_NEW', 'FILE_ANALYSIS_TOTAL', '10')");

        // Pro Level Limits (HOURLY + MONTHLY)
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_PRO', 'MESSAGES_HOURLY', '100')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_PRO', 'MESSAGES_MONTHLY', '5000')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_PRO', 'IMAGES_MONTHLY', '50')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_PRO', 'VIDEOS_MONTHLY', '10')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_PRO', 'AUDIOS_MONTHLY', '20')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_PRO', 'FILE_ANALYSIS_MONTHLY', '200')");

        // Team Level Limits (HOURLY + MONTHLY)
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_TEAM', 'MESSAGES_HOURLY', '300')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_TEAM', 'MESSAGES_MONTHLY', '15000')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_TEAM', 'IMAGES_MONTHLY', '200')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_TEAM', 'VIDEOS_MONTHLY', '50')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_TEAM', 'AUDIOS_MONTHLY', '100')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_TEAM', 'FILE_ANALYSIS_MONTHLY', '1000')");

        // Business Level Limits (HOURLY + MONTHLY)
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_BUSINESS', 'MESSAGES_HOURLY', '1000')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_BUSINESS', 'MESSAGES_MONTHLY', '50000')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_BUSINESS', 'IMAGES_MONTHLY', '1000')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_BUSINESS', 'VIDEOS_MONTHLY', '200')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_BUSINESS', 'AUDIOS_MONTHLY', '500')");
        $this->addSql("INSERT INTO BCONFIG (BOWNERID, BGROUP, BSETTING, BVALUE) VALUES (0, 'RATELIMITS_BUSINESS', 'FILE_ANALYSIS_MONTHLY', '5000')");
    }

    public function down(Schema $schema): void
    {
        // Remove all rate limiting configuration data
        $this->addSql("DELETE FROM BCONFIG WHERE BGROUP LIKE 'RATELIMITS_%' AND BOWNERID = 0");
        $this->addSql("DELETE FROM BCONFIG WHERE BGROUP = 'SYSTEM_FLAGS' AND BOWNERID = 0");
    }
}

